name: Release Binary

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

env:
  DOTNET_VERSION: '5.0.102'
  APPVERSION: '1.0'

jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:

      # Checkout the repo
      - uses: actions/checkout@master
      
      # Setup .NET Core SDK
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }} 

      - name: version
        run: |
          dotnet version --project-file reddit-importer.csproj --new-version '${{ env.APPVERSION }}.${{ env.GITHUB_RUN_NUMBER }}'

      # Run dotnet build and publish
      - name: dotnet build and publish
        run: |
          dotnet build --configuration Release
          dotnet publish -c Release -o ./publish

      - uses: papeloto/action-zip@v1
        with:
          files: publish/
          dest: publish.zip
          recursive: false
          
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: '${{ env.APPVERSION }}.${{ env.GITHUB_RUN_NUMBER }}'
          release_name: Release '${{ env.APPVERSION }}.${{ env.GITHUB_RUN_NUMBER }}'
          draft: false
          prerelease: false

      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ./publish.zip
          asset_name: subreddit-migrator-win10-x86.zip
          asset_content_type: application/zip